package com.linearity.utils;

import static com.linearity.utils.HookUtils.disableClass;
import static com.linearity.utils.HookUtils.disableClass_random;
import static com.linearity.utils.ReturnReplacements.returnNull;
import static com.linearity.utils.HookUtils.disableMethod;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.XposedHelpers;

public class HookerThread{
    public static final String[] TIMHookedPackagesPart3 = new String[]{
            "com.tencent.mobileqq.minigame.api.http.CustomX509TrustManager", "com.tencent.mobileqq.minigame.api.http.TritonHttpCallBack",
//            "com.tencent.mobileqq.minigame.api.http.TritonHttpProgressCallback", "com.tencent.mobileqq.minigame.api.http.TritonHttpResponseCallback",
//            "com.tencent.mobileqq.minigame.api.QQEnvImp", "com.tencent.mobileqq.minigame.data.BannerAdPosInfo",
//            "com.tencent.mobileqq.minigame.data.BlockAdInfo", "com.tencent.mobileqq.minigame.data.PublishMoodInfo",
            "com.tencent.mobileqq.minigame.debug.DebugWebSocket", "com.tencent.mobileqq.minigame.debug.QQDebugWebSocket",
            "com.tencent.mobileqq.minigame.gpkg.GpkgManager", "com.tencent.mobileqq.minigame.gpkg.MiniGamePkg",
//            "com.tencent.mobileqq.minigame.jsapi.callbacks.IGameUI", "com.tencent.mobileqq.minigame.jsapi.callbacks.PluginResultCallback",
            "com.tencent.mobileqq.minigame.jsapi.manager.CustomButtonManager", "com.tencent.mobileqq.minigame.jsapi.manager.GameVideoPlayerManager",
            "com.tencent.mobileqq.minigame.jsapi.manager.JsApiUpdateManager", "com.tencent.mobileqq.minigame.jsapi.manager.KeyboardHandler",
            "com.tencent.mobileqq.minigame.jsapi.manager.SystemInfoManager",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.CustomButtonPlugin",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.ImmersivePlugin", "com.tencent.mobileqq.minigame.jsapi.plugins.InputPlugin",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.OpenDataPlugin", "com.tencent.mobileqq.minigame.jsapi.plugins.OrientationPlugin",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.ReportPlugin", "com.tencent.mobileqq.minigame.jsapi.plugins.UDPPlugin",
            "com.tencent.mobileqq.minigame.jsapi.plugins.UpdateManagerPlugin",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.VideoPlugin",
//            "com.tencent.mobileqq.minigame.jsapi.plugins.WebAudioPlugin", "com.tencent.mobileqq.minigame.jsapi.webaudio.AudioContext",
//            "com.tencent.mobileqq.minigame.jsapi.webaudio.AudioDecoder",
            "com.tencent.mobileqq.minigame.jsapi.webaudio.WebAudioManager",
//            "com.tencent.mobileqq.minigame.jsapi.widgets.CustomButton", "com.tencent.mobileqq.minigame.jsapi.widgets.KeyboardLayout",
//            "com.tencent.mobileqq.minigame.jsapi.GameBrandRuntime", "com.tencent.mobileqq.minigame.jsapi.GameJsPluginEngine",
//            "com.tencent.mobileqq.minigame.jsapi.GameJsRuntime", "com.tencent.mobileqq.minigame.manager.AbstractDownloader",
            "com.tencent.mobileqq.minigame.manager.BannerAdViolationManager", "com.tencent.mobileqq.minigame.manager.BlockAdManager",
            "com.tencent.mobileqq.minigame.manager.DefaultDownloader", "com.tencent.mobileqq.minigame.manager.DefaultEngineLoader",
            "com.tencent.mobileqq.minigame.manager.EngineChannel", "com.tencent.mobileqq.minigame.manager.EngineInstaller",
            "com.tencent.mobileqq.minigame.manager.EngineManager", "com.tencent.mobileqq.minigame.manager.EngineVersion",
            "com.tencent.mobileqq.minigame.manager.FileDownloadManager", "com.tencent.mobileqq.minigame.manager.GameCloseManager",
            "com.tencent.mobileqq.minigame.manager.GameEngineWrapper", "com.tencent.mobileqq.minigame.manager.GameEnvManager",
            "com.tencent.mobileqq.minigame.manager.GameGrowthGuardianManager", "com.tencent.mobileqq.minigame.manager.GameInfoManager",
            "com.tencent.mobileqq.minigame.manager.GamePreConnectManager", "com.tencent.mobileqq.minigame.manager.GameReportManager",
            "com.tencent.mobileqq.minigame.manager.GameRuntimeLoader", "com.tencent.mobileqq.minigame.manager.GameRuntimeLoaderManager",
            "com.tencent.mobileqq.minigame.manager.InstalledEngine", "com.tencent.mobileqq.minigame.manager.LocalGameEngine",
            "com.tencent.mobileqq.minigame.manager.MiniGameStorageExceedManager", "com.tencent.mobileqq.minigame.manager.PreloadManager",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountHeadLayout",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountHelper",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountIPCModule",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountNavBar",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountViewPagerIndicator",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountWebFragment",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountWebView",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountWebViewBuilder",
//            "com.tencent.mobileqq.minigame.publicaccount.MiniGamePublicAccountWebViewJsPlugin",
//            "com.tencent.mobileqq.minigame.report.MiniGameBeaconReport", "com.tencent.mobileqq.minigame.splash.SplashMiniGameData",
//            "com.tencent.mobileqq.minigame.splash.SplashMiniGameDownloadManager", "com.tencent.mobileqq.minigame.splash.SplashMiniGameStarter",
//            "com.tencent.mobileqq.minigame.splash.SplashMiniGameUtil",
            "com.tencent.mobileqq.minigame.task.GameJsPluginEngineTask",
            "com.tencent.mobileqq.minigame.task.GpkgLoadAsyncTask", "com.tencent.mobileqq.minigame.task.InitGameRuntimeTask",
            "com.tencent.mobileqq.minigame.task.LaunchEngineUISteps", "com.tencent.mobileqq.minigame.task.TritonEngineInitTask",
//            "com.tencent.mobileqq.minigame.ui.GameActivity", "com.tencent.mobileqq.minigame.ui.GameActivity1", "com.tencent.mobileqq.minigame.ui.GameActivity2",
//            "com.tencent.mobileqq.minigame.ui.GameActivity3", "com.tencent.mobileqq.minigame.ui.GameActivity4", "com.tencent.mobileqq.minigame.ui.GameActivity5",
//            "com.tencent.mobileqq.minigame.ui.GameActivity6", "com.tencent.mobileqq.minigame.ui.GameBannerAdFragment",
//            "com.tencent.mobileqq.minigame.ui.InternalGameActivity", "com.tencent.mobileqq.minigame.ui.MiniGameAdBannerPopup",
//            "com.tencent.mobileqq.minigame.ui.MiniGamePayFragment", "com.tencent.mobileqq.minigame.ui.NavigatorBarForMiniGame",
//            "com.tencent.mobileqq.minigame.ui.VConsoleDragView", "com.tencent.mobileqq.minigame.ui.VConsoleView",
//            "com.tencent.mobileqq.minigame.utils.thread.TTHandleThread", "com.tencent.mobileqq.minigame.utils.AppUtil",
//            "com.tencent.mobileqq.minigame.utils.AssetsUtil", "com.tencent.mobileqq.minigame.utils.CPUUtil",
//            "com.tencent.mobileqq.minigame.utils.DeviceUtil", "com.tencent.mobileqq.minigame.utils.DpUtil",
//            "com.tencent.mobileqq.minigame.utils.FileUtils", "com.tencent.mobileqq.minigame.utils.GameActivityStatusWatcher",
//            "com.tencent.mobileqq.minigame.utils.GameLog", "com.tencent.mobileqq.minigame.utils.GameWnsUtils",
//            "com.tencent.mobileqq.minigame.utils.LogFilterUtil", "com.tencent.mobileqq.minigame.utils.NativeBuffer",
//            "com.tencent.mobileqq.minigame.utils.PathUtil", "com.tencent.mobileqq.minigame.utils.TxLibSoLoader",
//            "com.tencent.mobileqq.minigame.utils.VConsoleLogManager", "com.tencent.mobileqq.minigame.utils.VConsoleManager",
//            "com.tencent.mobileqq.minigame.widget.BlockAdView", "com.tencent.mobileqq.minigame.widget.DragLinearLayout",
//            "com.tencent.mobileqq.wifi.QWifiBaseFragment", "com.tencent.mobileqq.wifi.QWifiFloorFragment",
//            "com.tencent.mobileqq.wifi.QWifiListFragment", "com.tencent.mobileqq.wifi.QWifiSecurityFragment",
//            "com.tencent.mobileqq.vip.diy.common.DIYImageView", "com.tencent.mobileqq.vip.diy.template.ProfileCardDiyPhotoWallView",
//            "com.tencent.mobileqq.vip.diy.template.QZoneLayoutTemplate1", "com.tencent.mobileqq.vip.diy.template.QZoneLayoutTemplateBase",
//            "com.tencent.mobileqq.vip.diy.template.TemplatePhotoWall", "com.tencent.mobileqq.vip.diy.ETTextViewPlus",
//            "com.tencent.mobileqq.vip.diy.ProfileTemplateNickNameContainer", "com.tencent.mobileqq.vip.diy.TemplateLikeView",
//            "com.tencent.mobileqq.vip.lianghao.fragment.LiangHaoBuyFragment", "com.tencent.mobileqq.vip.lianghao.view.LiangHaoDialogView",
//            "com.tencent.mobileqq.vip.lianghao.view.LiangHaoView", "com.tencent.mobileqq.vip.lianghao.view.RegisterLiangHaoChoiceLayoutView",
//            "com.tencent.mobileqq.vip.lianghao.view.RegisterLiangHaoPayFailLayoutView", "com.tencent.mobileqq.vip.lianghao.RegisterLHAssistant$2",
//            "com.tencent.mobileqq.vip.AioVipKeywordHelper$1", "com.tencent.mobileqq.vip.KCWraperV2$1",
//            "com.tencent.mobileqq.vip.KingCardActivationFragment", "com.tencent.mobileqq.vipav.VipFullScreenVideoView",
//            "com.tencent.mobileqq.vipav.VipFunCallPreviewActivity", "com.tencent.mobileqq.voicechange.QQVoiceChangerThread",
//            "com.tencent.mobileqq.voicechange.VoiceChange","com.tencent.bugly.crashreport.biz.a",
    };
    public static final String[] TIMHookedPackagesPart2 = new String[]{
            "com.xiaomi.channel.commonutils.android.b", "com.xiaomi.channel.commonutils.android.c",
            "com.xiaomi.channel.commonutils.android.d", "com.xiaomi.channel.commonutils.android.e",
            "com.xiaomi.channel.commonutils.android.f", "com.xiaomi.channel.commonutils.android.g",
            "com.xiaomi.channel.commonutils.android.h", "com.xiaomi.channel.commonutils.android.i",
            "com.xiaomi.channel.commonutils.android.j", "com.xiaomi.channel.commonutils.file.a",
            "com.xiaomi.channel.commonutils.file.b", "com.xiaomi.channel.commonutils.file.c",
            "com.xiaomi.channel.commonutils.logger.a", "com.xiaomi.channel.commonutils.logger.b",
            "com.xiaomi.channel.commonutils.logger.LoggerInterface", "com.xiaomi.channel.commonutils.misc.a",
            "com.xiaomi.channel.commonutils.misc.b", "com.xiaomi.channel.commonutils.misc.c",
            "com.xiaomi.channel.commonutils.misc.d", "com.xiaomi.channel.commonutils.misc.e",
            "com.xiaomi.channel.commonutils.misc.f", "com.xiaomi.channel.commonutils.misc.g",
            "com.xiaomi.channel.commonutils.misc.h", "com.xiaomi.channel.commonutils.misc.i",
            "com.xiaomi.channel.commonutils.misc.j", "com.xiaomi.channel.commonutils.misc.k",
            "com.xiaomi.channel.commonutils.network.a", "com.xiaomi.channel.commonutils.network.b",
            "com.xiaomi.channel.commonutils.network.c", "com.xiaomi.channel.commonutils.network.d",
            "com.xiaomi.channel.commonutils.reflect.a", "com.xiaomi.channel.commonutils.stats.a",
            "com.xiaomi.channel.commonutils.string.a", "com.xiaomi.channel.commonutils.string.b",
            "com.xiaomi.channel.commonutils.string.c", "com.xiaomi.channel.commonutils.string.d",
            "com.xiaomi.measite.smack.a", "com.xiaomi.measite.smack.b", "com.xiaomi.metok.geofencing.a",
            "com.xiaomi.metok.geofencing.b", "com.xiaomi.metok.geofencing.c", "com.xiaomi.mipush.sdk.a",
            "com.xiaomi.mipush.sdk.aa", "com.xiaomi.mipush.sdk.ab", "com.xiaomi.mipush.sdk.c", "com.xiaomi.mipush.sdk.Constants",
            "com.xiaomi.mipush.sdk.d", "com.xiaomi.mipush.sdk.e", "com.xiaomi.mipush.sdk.ErrorCode", "com.xiaomi.mipush.sdk.f",
            "com.xiaomi.mipush.sdk.g", "com.xiaomi.mipush.sdk.h", "com.xiaomi.mipush.sdk.i", "com.xiaomi.mipush.sdk.j",
            "com.xiaomi.mipush.sdk.k", "com.xiaomi.mipush.sdk.l", "com.xiaomi.mipush.sdk.Logger", "com.xiaomi.mipush.sdk.m",
            "com.xiaomi.mipush.sdk.MessageHandleService", "com.xiaomi.mipush.sdk.MiPushClient",
            "com.xiaomi.mipush.sdk.MiPushCommandMessage", "com.xiaomi.mipush.sdk.MiPushMessage",
            "com.xiaomi.mipush.sdk.MiTinyDataClient", "com.xiaomi.mipush.sdk.n", "com.xiaomi.mipush.sdk.o",
            "com.xiaomi.mipush.sdk.p", "com.xiaomi.mipush.sdk.PushMessageHandler", "com.xiaomi.mipush.sdk.PushMessageHelper",
            "com.xiaomi.mipush.sdk.PushMessageReceiver", "com.xiaomi.mipush.sdk.PushServiceReceiver", "com.xiaomi.mipush.sdk.q",
            "com.xiaomi.mipush.sdk.r", "com.xiaomi.mipush.sdk.s", "com.xiaomi.mipush.sdk.t", "com.xiaomi.mipush.sdk.u",
            "com.xiaomi.mipush.sdk.v", "com.xiaomi.mipush.sdk.w", "com.xiaomi.mipush.sdk.x", "com.xiaomi.mipush.sdk.y",
            "com.xiaomi.mipush.sdk.z", "com.xiaomi.network.usagedemo.HostManagerDemo", "com.xiaomi.network.a",
            "com.xiaomi.network.AccessHistory", "com.xiaomi.network.b", "com.xiaomi.network.c", "com.xiaomi.network.Fallback",
            "com.xiaomi.network.Fallbacks", "com.xiaomi.network.Host", "com.xiaomi.network.HostFilter", "com.xiaomi.network.HostManager",
            "com.xiaomi.network.HostManagerV2", "com.xiaomi.network.HostRefreshService", "com.xiaomi.network.HttpProcessor",
            "com.xiaomi.network.HttpUtils", "com.xiaomi.network.NetworkStatusChangeReceiver", "com.xiaomi.push.log.a",
            "com.xiaomi.push.log.b", "com.xiaomi.push.log.c", "com.xiaomi.push.log.d", "com.xiaomi.push.log.e",
            "com.xiaomi.push.log.f", "com.xiaomi.push.log.g", "com.xiaomi.push.protobuf.a", "com.xiaomi.push.protobuf.b",
            "com.xiaomi.push.providers.a", "com.xiaomi.push.service.module.a", "com.xiaomi.push.service.module.b",
            "com.xiaomi.push.service.module.c", "com.xiaomi.push.service.module.d", "com.xiaomi.push.service.module.e",
            "com.xiaomi.push.service.module.f", "com.xiaomi.push.service.receivers.a", "com.xiaomi.push.service.receivers.NetworkStatusReceiver",
            "com.xiaomi.push.service.receivers.PingReceiver", "com.xiaomi.push.service.receivers.PkgUninstallReceiver",
            "com.xiaomi.push.service.timers.a", "com.xiaomi.push.service.timers.b", "com.xiaomi.push.service.timers.c",
            "com.xiaomi.push.service.a", "com.xiaomi.push.service.aa", "com.xiaomi.push.service.ab", "com.xiaomi.push.service.ac",
            "com.xiaomi.push.service.ad", "com.xiaomi.push.service.ae", "com.xiaomi.push.service.af", "com.xiaomi.push.service.ag",
            "com.xiaomi.push.service.ah", "com.xiaomi.push.service.ai", "com.xiaomi.push.service.aj", "com.xiaomi.push.service.ak",
            "com.xiaomi.push.service.al", "com.xiaomi.push.service.am", "com.xiaomi.push.service.an", "com.xiaomi.push.service.ao",
            "com.xiaomi.push.service.ap", "com.xiaomi.push.service.aq", "com.xiaomi.push.service.ar", "com.xiaomi.push.service.as",
            "com.xiaomi.push.service.at", "com.xiaomi.push.service.au", "com.xiaomi.push.service.av", "com.xiaomi.push.service.aw",
            "com.xiaomi.push.service.ay", "com.xiaomi.push.service.az", "com.xiaomi.push.service.b", "com.xiaomi.push.service.ba",
            "com.xiaomi.push.service.bb", "com.xiaomi.push.service.bc", "com.xiaomi.push.service.bd", "com.xiaomi.push.service.be",
            "com.xiaomi.push.service.bf", "com.xiaomi.push.service.bg", "com.xiaomi.push.service.bh", "com.xiaomi.push.service.bi",
            "com.xiaomi.push.service.bj", "com.xiaomi.push.service.bk", "com.xiaomi.push.service.bl", "com.xiaomi.push.service.bm",
            "com.xiaomi.push.service.c", "com.xiaomi.push.service.d", "com.xiaomi.push.service.e", "com.xiaomi.push.service.f",
            "com.xiaomi.push.service.g", "com.xiaomi.push.service.h", "com.xiaomi.push.service.i", "com.xiaomi.push.service.k",
            "com.xiaomi.push.service.l", "com.xiaomi.push.service.m", "com.xiaomi.push.service.n", "com.xiaomi.push.service.o",
            "com.xiaomi.push.service.p", "com.xiaomi.push.service.PacketSync", "com.xiaomi.push.service.q", "com.xiaomi.push.service.r",
            "com.xiaomi.push.service.s", "com.xiaomi.push.service.t", "com.xiaomi.push.service.u", "com.xiaomi.push.service.v",
            "com.xiaomi.push.service.w", "com.xiaomi.push.service.x", "com.xiaomi.push.service.XMJobService",
            "com.xiaomi.push.service.XMPushService", "com.xiaomi.push.service.y", "com.xiaomi.push.service.z",
            "com.xiaomi.push.thrift.a", "com.xiaomi.push.thrift.b", "com.xiaomi.push.thrift.c", "com.xiaomi.slim.a",
            "com.xiaomi.slim.b", "com.xiaomi.slim.c", "com.xiaomi.slim.d", "com.xiaomi.slim.e", "com.xiaomi.slim.f",
            "com.xiaomi.slim.g", "com.xiaomi.smack.debugger.a", "com.xiaomi.smack.filter.a", "com.xiaomi.smack.packet.a",
            "com.xiaomi.smack.packet.b", "com.xiaomi.smack.packet.c", "com.xiaomi.smack.packet.d", "com.xiaomi.smack.packet.e",
            "com.xiaomi.smack.packet.f", "com.xiaomi.smack.packet.g", "com.xiaomi.smack.packet.h", "com.xiaomi.smack.provider.a",
            "com.xiaomi.smack.provider.b", "com.xiaomi.smack.provider.c", "com.xiaomi.smack.util.a", "com.xiaomi.smack.util.b",
            "com.xiaomi.smack.util.c", "com.xiaomi.smack.util.d", "com.xiaomi.smack.util.e", "com.xiaomi.smack.util.f",
            "com.xiaomi.smack.util.g", "com.xiaomi.smack.util.h", "com.xiaomi.smack.a", "com.xiaomi.smack.b", "com.xiaomi.smack.c",
            "com.xiaomi.smack.d", "com.xiaomi.smack.e", "com.xiaomi.smack.f", "com.xiaomi.smack.g", "com.xiaomi.smack.h",
            "com.xiaomi.smack.i", "com.xiaomi.smack.j", "com.xiaomi.smack.k", "com.xiaomi.smack.l", "com.xiaomi.stats.a",
            "com.xiaomi.stats.b", "com.xiaomi.stats.c", "com.xiaomi.stats.d", "com.xiaomi.stats.e", "com.xiaomi.stats.f",
            "com.xiaomi.stats.g", "com.xiaomi.stats.h", "com.xiaomi.xmpush.thrift.a", "com.xiaomi.xmpush.thrift.aa",
            "com.xiaomi.xmpush.thrift.ab", "com.xiaomi.xmpush.thrift.ac", "com.xiaomi.xmpush.thrift.ad",
            "com.xiaomi.xmpush.thrift.ae", "com.xiaomi.xmpush.thrift.af", "com.xiaomi.xmpush.thrift.ag",
            "com.xiaomi.xmpush.thrift.ah", "com.xiaomi.xmpush.thrift.ai", "com.xiaomi.xmpush.thrift.aj",
            "com.xiaomi.xmpush.thrift.ak", "com.xiaomi.xmpush.thrift.al", "com.xiaomi.xmpush.thrift.am",
            "com.xiaomi.xmpush.thrift.an", "com.xiaomi.xmpush.thrift.ao", "com.xiaomi.xmpush.thrift.ap",
            "com.xiaomi.xmpush.thrift.aq", "com.xiaomi.xmpush.thrift.b", "com.xiaomi.xmpush.thrift.c",
            "com.xiaomi.xmpush.thrift.d", "com.xiaomi.xmpush.thrift.e", "com.xiaomi.xmpush.thrift.f",
            "com.xiaomi.xmpush.thrift.g", "com.xiaomi.xmpush.thrift.h", "com.xiaomi.xmpush.thrift.i",
            "com.xiaomi.xmpush.thrift.j", "com.xiaomi.xmpush.thrift.k", "com.xiaomi.xmpush.thrift.l",
            "com.xiaomi.xmpush.thrift.m", "com.xiaomi.xmpush.thrift.n", "com.xiaomi.xmpush.thrift.o",
            "com.xiaomi.xmpush.thrift.p", "com.xiaomi.xmpush.thrift.q", "com.xiaomi.xmpush.thrift.r",
            "com.xiaomi.xmpush.thrift.s", "com.xiaomi.xmpush.thrift.t", "com.xiaomi.xmpush.thrift.u",
            "com.xiaomi.xmpush.thrift.v", "com.xiaomi.xmpush.thrift.w", "com.xiaomi.xmpush.thrift.x",
            "com.xiaomi.xmpush.thrift.y", "com.xiaomi.xmpush.thrift.z",
    };

    public static final String[] TIMHookedPackagesPart1 = new String[]{
//            "com.tencent.mobileqq.gamecenter.anim.FullPopAnimLowVersion$6",
//            "com.tencent.mobileqq.gamecenter.anim.FullPopAnimWithLOLLIPOP$5",
//            "com.tencent.mobileqq.gamecenter.data.FeedsItemData",
//            "com.tencent.mobileqq.gamecenter.data.FullPopData",
//            "com.tencent.mobileqq.gamecenter.data.GameCenterSessionInfo",
//            "com.tencent.mobileqq.gamecenter.data.GameNoticeCenter",
//            "com.tencent.mobileqq.gamecenter.data.GameNoticeInfo",
//            "com.tencent.mobileqq.gamecenter.data.PadFaceAd",
//            "com.tencent.mobileqq.gamecenter.fragment.QQGamePadFaceFragment",
//            "com.tencent.mobileqq.gamecenter.fragment.QQGamePubAccountFragment",
//            "com.tencent.mobileqq.gamecenter.media.GameCenterVideoViewController",
//            "com.tencent.mobileqq.gamecenter.message.GameBasicInfo", "com.tencent.mobileqq.gamecenter.message.GameSwitchConfig",
//            "com.tencent.mobileqq.gamecenter.message.GameUserInfo", "com.tencent.mobileqq.gamecenter.message.TinyInfo",
//            "com.tencent.mobileqq.gamecenter.message.UinToTinyId", "com.tencent.mobileqq.gamecenter.protocol.GetArkTailReq",
//            "com.tencent.mobileqq.gamecenter.protocol.GetArkTailRsp",
            "com.tencent.mobileqq.gamecenter.protocol.ReportTypeReq",
            "com.tencent.mobileqq.gamecenter.protocol.ReportTypeRsp",
//            "com.tencent.mobileqq.gamecenter.view.ArkHeaderView",
//            "com.tencent.mobileqq.gamecenter.view.FullPopVideoView", "com.tencent.mobileqq.gamecenter.view.GameArkView",
//            "com.tencent.mobileqq.gamecenter.view.GameSessionView", "com.tencent.mobileqq.gamecenter.view.ImgHeaderView",
//            "com.tencent.mobileqq.gamecenter.view.MoreMsgHeaderView", "com.tencent.mobileqq.gamecenter.view.NavBarQQGamePub",
//            "com.tencent.mobileqq.gamecenter.view.QQGameIndicator", "com.tencent.mobileqq.gamecenter.view.QQGamePubAccountFloatView",
//            "com.tencent.mobileqq.gamecenter.view.QQGamePubViewpager", "com.tencent.mobileqq.gamecenter.view.QQGameStatusView",
//            "com.tencent.mobileqq.gamecenter.view.ScrollLinearLayout", "com.tencent.mobileqq.gamecenter.view.ScrollTextView",

//                            "com.tencent.mobileqq.gamecenter.view.ShadowView",

//            "com.tencent.mobileqq.gamecenter.view.TextHeaderView",
//            "com.tencent.mobileqq.gamecenter.view.VideoLoadingImage", "com.tencent.mobileqq.gamecenter.web.view.BaseLayout",
//            "com.tencent.mobileqq.gamecenter.web.view.BaseNestHeaderLayout", "com.tencent.mobileqq.gamecenter.web.view.BaseNestScrollWebView",
//            "com.tencent.mobileqq.gamecenter.web.view.GameContentView", "com.tencent.mobileqq.gamecenter.web.view.QQGameHeadLayout",
//            "com.tencent.mobileqq.gamecenter.web.view.QQGamePubWebView", "com.tencent.mobileqq.gamecenter.web.QQGameFeedWebFragment",
//            "com.tencent.mobileqq.gamecenter.web.QQGameMsgInfo", "com.tencent.mobileqq.gamecenter.web.QQGamePubActivity",
//            "com.tencent.qqmini.proxyimpl.AdProxyImpl",
            "com.tencent.qqmini.minigame.action.DebugSocketAction",
//            "com.tencent.qqmini.minigame.action.GetLastClickAction", "com.tencent.qqmini.minigame.action.OperateCustomButton",
//            "com.tencent.qqmini.minigame.api.QQEnvImp",
            "com.tencent.qqmini.minigame.debug.DebugWebSocket",
            "com.tencent.qqmini.minigame.debug.QQDebugWebSocket", "com.tencent.qqmini.minigame.gpkg.ApkgMainProcessManager",
            "com.tencent.qqmini.minigame.manager.CustomButtonManager", "com.tencent.qqmini.minigame.manager.GameCloseManager",
            "com.tencent.qqmini.minigame.manager.GameEngineWrapper", "com.tencent.qqmini.minigame.manager.GameEnvManager",
            "com.tencent.qqmini.minigame.manager.GameInfoManager", "com.tencent.qqmini.minigame.manager.GameReportManager",
            "com.tencent.qqmini.minigame.manager.GameVideoPlayerManager", "com.tencent.qqmini.minigame.manager.JsApiUpdateManager",
            "com.tencent.qqmini.minigame.gpkg.GpkgManager", "com.tencent.qqmini.minigame.action.GetGameInfoManager",
            "com.tencent.qqmini.minigame.plugins.UpdateManagerJsPlugin","com.tencent.biz.pubaccount.readinjoy.engine.KandianMergeManager",
//            "com.tencent.qqmini.minigame.gpkg.MiniGamePkg", "com.tencent.qqmini.minigame.model.BlockAdInfo",
//            "com.tencent.qqmini.minigame.plugins.BlockAdPlugin",
//            "com.tencent.qqmini.minigame.plugins.CustomButtonPlugin", "com.tencent.qqmini.minigame.plugins.GameDataJsPlugin",
//            "com.tencent.qqmini.minigame.plugins.GameSystemInfoPlugin", "com.tencent.qqmini.minigame.plugins.ImmersiveJsPlugin",
//            "com.tencent.qqmini.minigame.plugins.OpenDataJsPlugin", "com.tencent.qqmini.minigame.plugins.OrientationJsPlugin",
//            "com.tencent.qqmini.minigame.plugins.ProfileJsPlugin", "com.tencent.qqmini.minigame.plugins.SubpackageJsPlugin",
//            "com.tencent.qqmini.minigame.plugins.UDPJsPlugin",
//            "com.tencent.qqmini.minigame.plugins.VideoJsPlugin", "com.tencent.qqmini.minigame.plugins.WebAudioPlugin",
//            "com.tencent.qqmini.minigame.proxy.MiniGameCmdProxyImpl", "com.tencent.qqmini.minigame.report.MiniGameBeaconReport",
            "com.tencent.qqmini.minigame.task.GameRuntimeCreateTask", "com.tencent.qqmini.minigame.task.GpkgLoadAsyncTask",
            "com.tencent.qqmini.minigame.task.InitGameRuntimeTask", "com.tencent.qqmini.minigame.task.TritonEngineInitTask",
//            "com.tencent.qqmini.minigame.task.LaunchEngineUISteps",
//            "com.tencent.qqmini.minigame.ui.GameRuntimeStateObserver",
//            "com.tencent.qqmini.minigame.ui.GameUIProxy", "com.tencent.qqmini.minigame.ui.LoadingStatus",
//            "com.tencent.qqmini.minigame.ui.LoadingUI", "com.tencent.qqmini.minigame.ui.MiniGameAdBannerPopup",
//            "com.tencent.qqmini.minigame.ui.VConsoleDragView", "com.tencent.qqmini.minigame.ui.VConsoleView",
//            "com.tencent.qqmini.minigame.utils.CPUUtil", "com.tencent.qqmini.minigame.utils.GameActivityStatusWatcher",
//            "com.tencent.qqmini.minigame.utils.GameLog", "com.tencent.qqmini.minigame.utils.LogFilterUtil",
//            "com.tencent.qqmini.minigame.utils.MD5FileUtil", "com.tencent.qqmini.minigame.utils.PathUtil",
//            "com.tencent.qqmini.minigame.utils.TTHandleThread",
            "com.tencent.qqmini.minigame.utils.VConsoleLogManager",
            "com.tencent.qqmini.minigame.utils.VConsoleManager", "com.tencent.qqmini.minigame.webaudio.WebAudioManager",
//            "com.tencent.qqmini.minigame.webaudio.AudioContext",
//            "com.tencent.qqmini.minigame.webaudio.AudioDecoder",
//            "com.tencent.qqmini.minigame.widget.CustomButton", "com.tencent.qqmini.minigame.widget.DragLinearLayout",
//            "com.tencent.qqmini.minigame.widget.GameCapsuleButtonClickListener", "com.tencent.qqmini.minigame.widget.GameNavigationBar",
//            "com.tencent.qqmini.minigame.BuildConfig", "com.tencent.qqmini.minigame.GameConst",
//            "com.tencent.qqmini.minigame.GameJsPluginEngine", "com.tencent.qqmini.minigame.GameJsService",
//            "com.tencent.qqmini.minigame.GamePage", "com.tencent.qqmini.minigame.GameRuntime",
            "com.tencent.qqmini.minigame.GameRuntimeLoader",
//            "com.tencent.qqmini.minigame.R",
            "com.tencent.ad.tangram.analysis.AdABTest",
//            "com.tencent.ad.tangram.analysis.AdAnalysis",
//            "com.tencent.ad.tangram.analysis.BuildConfig", "com.tencent.ad.tangram.ark.AdArkAdapter",
//            "com.tencent.ad.tangram.ark.AdArkView", "com.tencent.ad.tangram.base.BuildConfig",
//            "com.tencent.ad.tangram.canvas.download.AdCanvasDownloadListener",
//            "com.tencent.ad.tangram.canvas.download.AdCanvasDownloadListenerAdapter",
//            "com.tencent.ad.tangram.canvas.download.AdDownloadConstants", "com.tencent.ad.tangram.canvas.download.AdDownloader",
//            "com.tencent.ad.tangram.canvas.download.AdDownloaderAdapter",
            "com.tencent.ad.tangram.canvas.download.AdDownloadTask", "com.tencent.ad.tangram.canvas.download.AdDownloadTaskAdapter",
//            "com.tencent.ad.tangram.canvas.download.IAdDownloader",
//            "com.tencent.ad.tangram.canvas.report.AdDMPReportUtil", "com.tencent.ad.tangram.canvas.report.AdRefreshCallback",
//            "com.tencent.ad.tangram.canvas.report.AdReport", "com.tencent.ad.tangram.canvas.report.AdReportAdapter",
//            "com.tencent.ad.tangram.canvas.resource.AdResource", "com.tencent.ad.tangram.canvas.resource.AdResourceAdapter",
//            "com.tencent.ad.tangram.canvas.statistics.AdTimeStatistics", "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.AdAppBtnData",
            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.AdAppDownloadManager",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.b", "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.c",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.d", "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.e",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.f", "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.g",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appbutton.h", "com.tencent.ad.tangram.canvas.views.canvas.components.appIcon.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.appIcon.b", "com.tencent.ad.tangram.canvas.views.canvas.components.button.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.button.b", "com.tencent.ad.tangram.canvas.views.canvas.components.fixedbutton.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.fixedbutton.b", "com.tencent.ad.tangram.canvas.views.canvas.components.fixedbutton.c",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.form.a", "com.tencent.ad.tangram.canvas.views.canvas.components.form.b",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.imagesCarousel.a", "com.tencent.ad.tangram.canvas.views.canvas.components.imagesCarousel.b",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.imagesCarousel.c", "com.tencent.ad.tangram.canvas.views.canvas.components.picture.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.picture.b", "com.tencent.ad.tangram.canvas.views.canvas.components.pictures.a",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.pictures.b", "com.tencent.ad.tangram.canvas.views.canvas.components.pictures.c",
//            "com.tencent.ad.tangram.canvas.views.canvas.components.roundview.a", "com.tencent.ad.tangram.canvas.views.canvas.components.roundview.b",
            "com.tencent.ad.tangram.canvas.views.canvas.components.text.a", "com.tencent.ad.tangram.canvas.views.canvas.components.text.b",
            "com.tencent.ad.tangram.canvas.views.canvas.components.AdCanvasComponentData", "com.tencent.ad.tangram.canvas.views.canvas.components.AdCanvasComponentView",
            "com.tencent.ad.tangram.canvas.views.canvas.framework.a", "com.tencent.ad.tangram.canvas.views.canvas.framework.AdCanvasPageView",
            "com.tencent.ad.tangram.canvas.views.canvas.framework.AdCanvasView", "com.tencent.ad.tangram.canvas.views.canvas.framework.AdCanvasViewListener",
            "com.tencent.ad.tangram.canvas.views.canvas.framework.b", "com.tencent.ad.tangram.canvas.views.canvas.AdCanvasData",
            "com.tencent.ad.tangram.canvas.views.canvas.AdCanvasDataBuilderV2", "com.tencent.ad.tangram.canvas.views.form.framework.AdFormCommitListener",
            "com.tencent.ad.tangram.canvas.views.form.framework.AdFormErrorListener", "com.tencent.ad.tangram.canvas.views.form.framework.AdFormItemData",
            "com.tencent.ad.tangram.canvas.views.form.framework.AdFormItemView", "com.tencent.ad.tangram.canvas.views.form.framework.AdFormTableData",
            "com.tencent.ad.tangram.canvas.views.form.AdFormData", "com.tencent.ad.tangram.canvas.views.form.AdFormError",
            "com.tencent.ad.tangram.canvas.views.form.AdFormViewListener", "com.tencent.ad.tangram.canvas.views.xijing.a",
            "com.tencent.ad.tangram.canvas.views.xijing.AdButtonView", "com.tencent.ad.tangram.canvas.views.xijing.AdTextData",
            "com.tencent.ad.tangram.canvas.views.AdViewStatus", "com.tencent.ad.tangram.canvas.AdCanvas", "com.tencent.ad.tangram.canvas.AdCanvasAdapter",
            "com.tencent.ad.tangram.canvas.AdCanvasJsonManager", "com.tencent.ad.tangram.dialog.AdProgressDialog",
            "com.tencent.ad.tangram.dialog.AdProgressDialogAdapter", "com.tencent.ad.tangram.image.AdImageViewAdapter",
            "com.tencent.ad.tangram.image.AdImageViewBuilder", "com.tencent.ad.tangram.ipc.AdIPCManager", "com.tencent.ad.tangram.json.a",
            "com.tencent.ad.tangram.json.AdJSON", "com.tencent.ad.tangram.json.BuildConfig", "com.tencent.ad.tangram.loader.AdLoader",
            "com.tencent.ad.tangram.loader.AdLoaderWithJSON", "com.tencent.ad.tangram.loader.BuildConfig", "com.tencent.ad.tangram.log.AdLog",
            "com.tencent.ad.tangram.log.AdLogAdapter", "com.tencent.ad.tangram.mini.AdQQMINIProgram", "com.tencent.ad.tangram.mini.AdQQMINIProgramAdapter",
            "com.tencent.ad.tangram.net.a", "com.tencent.ad.tangram.net.AdHttp", "com.tencent.ad.tangram.offline.AdOffline",
            "com.tencent.ad.tangram.offline.AdOfflineAdapter", "com.tencent.ad.tangram.process.AdProcessManager",
            "com.tencent.ad.tangram.process.AdProcessManagerAdapter", "com.tencent.ad.tangram.protocol.analysis.BuildConfig",
            "com.tencent.ad.tangram.protocol.enumeration.BuildConfig", "com.tencent.ad.tangram.protocol.BuildConfig",
            "com.tencent.ad.tangram.protocol.cps_info", "com.tencent.ad.tangram.protocol.experiment_v2", "com.tencent.ad.tangram.protocol.gdt_abtest",
            "com.tencent.ad.tangram.protocol.gdt_analysis_event", "com.tencent.ad.tangram.protocol.gdt_analysis_request",
            "com.tencent.ad.tangram.protocol.gdt_analysis_response", "com.tencent.ad.tangram.protocol.gdt_settings",
            "com.tencent.ad.tangram.protocol.indicator", "com.tencent.ad.tangram.protocol.landing_page_collect_data",
            "com.tencent.ad.tangram.protocol.pub_placement", "com.tencent.ad.tangram.protocol.qq_ad_get",
            "com.tencent.ad.tangram.protocol.qq_common", "com.tencent.ad.tangram.protocol.qzap_common", "com.tencent.ad.tangram.qq.BuildConfig",
            "com.tencent.ad.tangram.settings.AdSettingsUtil", "com.tencent.ad.tangram.settings.BuildConfig", "com.tencent.ad.tangram.statistics.a",
            "com.tencent.ad.tangram.statistics.AdAntiSpamForClick", "com.tencent.ad.tangram.statistics.AdReporterForClick",
            "com.tencent.ad.tangram.statistics.b", "com.tencent.ad.tangram.thread.AdThreadManager", "com.tencent.ad.tangram.thread.AdThreadManagerAdapter",
            "com.tencent.ad.tangram.toast.AdToast", "com.tencent.ad.tangram.toast.AdToastAdapter", "com.tencent.ad.tangram.util.a",
            "com.tencent.ad.tangram.util.AdAppDeeplinkLauncher", "com.tencent.ad.tangram.util.AdAppReceiver", "com.tencent.ad.tangram.util.AdAppUtil",
            "com.tencent.ad.tangram.util.AdClickUtil", "com.tencent.ad.tangram.util.AdExposureChecker", "com.tencent.ad.tangram.util.AdExposureListHolder",
            "com.tencent.ad.tangram.util.AdHexUtil", "com.tencent.ad.tangram.util.AdUIUtils", "com.tencent.ad.tangram.util.AdUriUtil",
            "com.tencent.ad.tangram.version.AdVersion", "com.tencent.ad.tangram.version.AdVersionAdapter", "com.tencent.ad.tangram.videoceiling.AdVideoCeiling",
            "com.tencent.ad.tangram.videoceiling.AdVideoCeilingAdapter", "com.tencent.ad.tangram.videoceiling.AdVideoSplice",
            "com.tencent.ad.tangram.videoceiling.AdVideoSpliceAdapter", "com.tencent.ad.tangram.web.AdBrowser", "com.tencent.ad.tangram.web.AdBrowserAdapter",
            "com.tencent.ad.tangram.a", "com.tencent.ad.tangram.Ad", "com.tencent.ad.tangram.AdBuilder", "com.tencent.ad.tangram.AdError",
            "com.tencent.ad.tangram.AdSettings", "com.tencent.ad.tangram.BuildConfig",
            "tju",//手动找到的ad加载

            "com.qq.android.dexposed.callbacks.IXUnhook", "com.qq.android.dexposed.callbacks.XCallback",
            "com.qq.android.dexposed.utility.Debug", "com.qq.android.dexposed.utility.Logger",
            "com.qq.android.dexposed.utility.NeverCalled", "com.qq.android.dexposed.utility.NougatPolicy",
            "com.qq.android.dexposed.utility.Platform", "com.qq.android.dexposed.utility.Runtime",
            "com.qq.android.dexposed.utility.Unsafe", "com.qq.android.dexposed.ClassUtils",
            "com.qq.android.dexposed.DeviceCheck", "com.qq.android.dexposed.DexposedBridge",
            "com.qq.android.dexposed.XC_MethodHook", "com.qq.android.dexposed.XC_MethodReplacement",
            "com.qq.android.dexposed.XposedHelpers",
            "com.wifisdk.ui.api.BaseFragImplManager",
            "com.wifisdk.ui.api.RProxy", "com.wifisdk.ui.fragments.BaseFragmentImpl",
            "com.wifisdk.ui.fragments.WifiSDKFloorFragImpl", "com.wifisdk.ui.fragments.WifiSDKMainFragImpl",
            "com.wifisdk.ui.fragments.WifiSDKSecurityFragImpl", "com.wifisdk.ui.view.a", "com.wifisdk.ui.view.b",
            "com.wifisdk.ui.view.c", "com.wifisdk.ui.view.d", "com.wifisdk.ui.view.e", "com.wifisdk.ui.view.WifiCommonView",
            "com.wifisdk.ui.WifiSDKUIApi",
//            "com.xiaomi.channel.commonutils.android.a",
            "aeiv",
    };

    public static final String[] TIMHookedPackagesPart4 = new String[]{
            "com.tencent.bugly.Bugly", "com.tencent.bugly.BuglyStrategy",
            "com.tencent.bugly.crashreport.biz.b", "com.tencent.bugly.crashreport.biz.UserInfoBean",
            "com.tencent.bugly.crashreport.common.info.a", "com.tencent.bugly.crashreport.common.info.AppInfo",
            "com.tencent.bugly.crashreport.common.info.b", "com.tencent.bugly.crashreport.common.info.PlugInBean",
            "com.tencent.bugly.crashreport.common.strategy.a", "com.tencent.bugly.crashreport.common.strategy.StrategyBean",
            "com.tencent.bugly.crashreport.crash.anr.a", "com.tencent.bugly.crashreport.crash.anr.b",
            "com.tencent.bugly.crashreport.crash.anr.TraceFileHelper", "com.tencent.bugly.crashreport.crash.jni.a",
            "com.tencent.bugly.crashreport.crash.jni.b", "com.tencent.bugly.crashreport.crash.jni.NativeCrashHandler",
            "com.tencent.bugly.crashreport.crash.jni.NativeExceptionHandler", "com.tencent.bugly.crashreport.crash.a",
             "com.tencent.bugly.crashreport.crash.BuglyBroadcastReceiver","com.tencent.bugly.crashreport.crash.CrashDetailBean",
//            "com.tencent.bugly.crashreport.crash.c", "com.tencent.bugly.crashreport.crash.b",
//            "com.tencent.bugly.crashreport.crash.d", "com.tencent.bugly.crashreport.crash.e",
//            "com.tencent.bugly.crashreport.crash.f", "com.tencent.bugly.crashreport.a",
            "com.tencent.bugly.crashreport.BuglyHintException", "com.tencent.bugly.crashreport.BuglyLog",
//            "com.tencent.bugly.proguard.a", "com.tencent.bugly.proguard.aa", "com.tencent.bugly.proguard.ab",
//            "com.tencent.bugly.proguard.ac", "com.tencent.bugly.proguard.ad", "com.tencent.bugly.proguard.ae",
//            "com.tencent.bugly.proguard.af", "com.tencent.bugly.proguard.ag", "com.tencent.bugly.proguard.ah",
//            "com.tencent.bugly.proguard.ai", "com.tencent.bugly.proguard.aj", "com.tencent.bugly.proguard.ak",
//            "com.tencent.bugly.proguard.al", "com.tencent.bugly.proguard.am", "com.tencent.bugly.proguard.an",
//            "com.tencent.bugly.proguard.ao", "com.tencent.bugly.proguard.ap", "com.tencent.bugly.proguard.aq",
//            "com.tencent.bugly.proguard.ar", "com.tencent.bugly.proguard.b", "com.tencent.bugly.proguard.c",
//            "com.tencent.bugly.proguard.d", "com.tencent.bugly.proguard.e", "com.tencent.bugly.proguard.f",
//            "com.tencent.bugly.proguard.g", "com.tencent.bugly.proguard.h", "com.tencent.bugly.proguard.i",
//            "com.tencent.bugly.proguard.j", "com.tencent.bugly.proguard.k", "com.tencent.bugly.proguard.l",
//            "com.tencent.bugly.proguard.m", "com.tencent.bugly.proguard.n", "com.tencent.bugly.proguard.o",
//            "com.tencent.bugly.proguard.p", "com.tencent.bugly.proguard.q", "com.tencent.bugly.proguard.r",
//            "com.tencent.bugly.proguard.s", "com.tencent.bugly.proguard.t", "com.tencent.bugly.proguard.u",
//            "com.tencent.bugly.proguard.v", "com.tencent.bugly.proguard.w", "com.tencent.bugly.proguard.x",
            "com.tencent.bugly.proguard.y", "com.tencent.bugly.proguard.z", "com.tencent.bugly.a", "com.tencent.bugly.b",
            "com.tencent.feedback.eup.CrashReport",
            "com.tencent.ark.ArkDebugger",
            "com.tencent.smtt.sdk.TbsLogReport$TbsLogInfo",
            "com.tencent.mobileqq.msf.sdk.y",
            "com.tencent.mobileqq.msf.core.c.k",
            "com.tencent.mobileqq.Pandora.util.BackgroundUtil",
//            "eipc.EIPCClient",
//            "eipc.EIPCModuleManager",
            "cooperation.qzone.CrashGuard",
            "cooperation.qzone.QZoneCrashHandler",
            "com.tencent.mobileqq.gamecenter.message.GameMsgManager",
            "com.tencent.mobileqq.gamecenter.message.GameMsgManager$2",
            "com.tencent.qphone.base.util.QLog",
//            "com.tencent.mobileqq.msf.core.MsfCore",
//            "com.tencent.biz.qqstory.takevideo2.StoryPublishLauncher",
//            "com.tencent.biz.qqstory.takevideo2.StoryPublishLauncher$2",
            "ahsd",
//            "rlx",
//            "ayve"
//            "com.tencent.biz.qqstory.playvideo.player.mediaplayer.AudioPlayback$AudioThread"
    };
    private final String[][] classesToDisable;
    private final ClassLoader classLoader;
    private final boolean useRandom;
    public HookerThread(ClassLoader classLoader,boolean useRandom,String[]... classesToDisable){
        this.classesToDisable = classesToDisable;
        this.classLoader = classLoader;
        this.useRandom = useRandom;
    }

    public void run() {
        Class<?> hookClass;
        for (String[] sArr : classesToDisable) {
            for (String s:sArr){
                hookClass = XposedHelpers.findClassIfExists(s, classLoader);
                if (hookClass == null){continue;}
                if (useRandom){
                    disableClass_random(hookClass);
                }
                else {
                    disableClass(hookClass);
                }
            }
        }
    }
}
